### PR TITLE
Remove Jordan Liggitt from PSC (stepping down)

### PR DESCRIPTION
**Pull request by joelsmith**
Thanks @liggitt for all the work performed as a member of the PSC! I'm sure we'll continue to take advantage of your expertise when we work together on future issues. It's nice knowing that you're still around to weigh in when we need you!

### CODE REVIEW

**Comment by liggitt** [comment]
My pleasure. You know where to find me if you need me :)

**Comment by tallclair** [comment]
nit: we should also update https://github.com/kubernetes/security/blob/master/OWNERS_ALIASES and https://github.com/kubernetes/security/blob/master/SECURITY_CONTACTS

**Pull request merged**
