### PR TITLE
Add Sam Fowler as associate member

### PR DESCRIPTION
**Pull request by lukehinds**
I will mentor Sam Fowler with the view of graduation from associate
to full member of the PSC.

Sam Fowler is a senior analyst in Red Hat's Product Security team with a
focus on the Kubernetes based OpenShift product. On this team he is
responsible for response to security disclosures, handling embargoed
vulnerabilities, security hardening and productization. He has formerly
held developer and security testing roles at Boeing, Dolby and IBM.

### CODE REVIEW

**Comment by lukehinds** [comment]
I  am going to lazy consensus merge of this on Friday June 15th

**Comment by lukehinds** [comment]
@joelsmith / @tallclair @micahhausler et al.

could you lgtm / approve please? 

Sam will start working on #55, #56 and we should keep him in mind for any public issues that need handling.

**Comment by lukehinds** [comment]
tagging @cji & @cjcullen

could someone lgtm if no info is needed, would like to get same in the position to assign some issues to him.

**Comment by cji** [comment]
🎉 Welcome @sfowl!

**Comment by joelsmith** [comment]
Welcome, @sfowl, glad to have you aboard. I'm sure you'll have a lot to contribute.

**Pull request merged**
