### PR TITLE
security-release-process: update philips's email

### PR DESCRIPTION
**Pull request by philips**
Use redhat.com email over coreos.com email due to losing filters

### CODE REVIEW

**Comment by philips** [comment]
Gahh, @joelsmith can't approve because https://github.com/kubernetes/community/pull/3459 hasn't merged.

**Comment by joelsmith** [comment]
Looks like I haven't made it into the `OWNERS_ALIASES` file yet. Does that happen automatically after we update https://github.com/kubernetes/org/blob/master/config/kubernetes/org.yaml#L1852 or does it come from https://github.com/kubernetes/community/blob/master/sigs.yaml ?

**Comment by philips** [comment]
It comes from sigs AFAIK

**Comment by tallclair** [comment]
/approve

btw, is there a reason you have 2 emails here? https://github.com/kubernetes/security/blame/master/private-distributors-list.md#L53-L54

(actually, should we just remove all the PSC folks from there, and rely on the nested security@kubernetes.io?)

**Comment by philips** [comment]
I have two emails because I don't always have access to my work email when
on-call :-/

**Pull request merged**
