### PR TITLE
Add Tabitha Sable as an associate member

### PR DESCRIPTION
**Pull request by cji**
This PR requires at least 4 approvals from PSC members
- [x] @tabbysable 
- [x] @cjcullen 
- [x] @cji 
- [x] @joelsmith 
- [ ] @lukehinds 
- [ ] @micahhausler 
- [x] @swamymsft
- [x] @tallclair  

/hold

### CODE REVIEW

**Comment by cji** [comment]
Welcome @tabbysable!

**Comment by tabbysable** [comment]
Thank you!
/honk

**Pull request merged**
