### PR TITLE
Update private-distributors-list.md

### PR DESCRIPTION
**Pull request by swamymsft**
Adding Loodse to the private distribution list based on the application

### CODE REVIEW

**Comment by philips** [comment]
@swamymsft could you please add the application to the commit message as done with the canonical: https://github.com/kubernetes/security/commit/49b5e06484ebf71ff27f08f2212760e2617ab8ac#diff-49e086cea35a7ca0f86fae6ba77880c9

**Comment by swamymsft** [comment]
> @swamymsft could you please add the application to the commit message as done with the canonical: [49b5e06#diff-49e086cea35a7ca0f86fae6ba77880c9](https://github.com/kubernetes/security/commit/49b5e06484ebf71ff27f08f2212760e2617ab8ac#diff-49e086cea35a7ca0f86fae6ba77880c9)

done, does it look good now?

**Comment by philips** [comment]
Yes, but can you squash everything down?

**Comment by swamymsft** [comment]
> Yes, but can you squash everything down?

I squashed the commits.

**Pull request merged**
