### PR TITLE
Onboard Swamy to PSC

### PR DESCRIPTION
**Pull request by tallclair**
/assign @swamymsft

### CODE REVIEW

**Comment by tallclair** [comment]
Silly @k8s-ci-robot

**Comment by joelsmith** [comment]
It might be nice to document our consensus on a membership update like this, just for the record. I assume this action was discussed in the the recent PSC monthly meeting (which I unfortunately had to miss).

So, for the record, :+1: from me to adding @swamymsft. Welcome aboard!

**Comment by cji** [comment]
@joelsmith Apologies, I probably hit the / commands a little too quickly here.

**Pull request merged**
